------------------
select 'drop table ', table_name, 'cascade constraints;' from user_tables;
drop table 	HANHKHACH	cascade constraints;
drop table 	TAIKHOANNV	cascade constraints;
drop table 	NHANVIEN	cascade constraints;
drop table 	LICHSUVE	cascade constraints;
drop table 	CHUYENTAU	cascade constraints;
drop table 	TAIKHOANQL	cascade constraints;
drop table 	VETAU	cascade constraints;
--------------------------------
create table  "DOAN1"."HANHKHACH"
(
    "MAKH" NUMBER(8,0) PRIMARY KEY, 
    "MANV" NUMBER(8,0),
    "MAVE" NUMBER(8,0) , 
	"HOTEN" VARCHAR2(30 BYTE), 
	"GIOITINH" VARCHAR2(20 BYTE),
    "SOCMND" VARCHAR2(20 BYTE),
    "QUOCTICH" VARCHAR2(20 BYTE),
    "SDT" VARCHAR2(20 BYTE)
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ------------------------
create table "DOAN1"."TAIKHOANNV"
(  "ID" NUMBER(8,0) PRIMARY KEY,
	"MATKHAU" VARCHAR2(30 BYTE)
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  create table "DOAN1"."NHANVIEN"
(
    "MANV" NUMBER(8,0) PRIMARY KEY, 
	"HOTEN" VARCHAR2(30 BYTE), 
	"SOCMND"  VARCHAR2(20 BYTE),
    "ID" NUMBER(8,0),
	"GIOITINH" VARCHAR2(20 BYTE),
    "QUOCTICH" VARCHAR2(20 BYTE),
    "SDT" VARCHAR2(20 BYTE)

   

)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 create table "DOAN1"."VETAU"
(
    "MAVE" NUMBER(8,0) PRIMARY KEY,
    "MASOGHE" NUMBER(8,0),
    "GADI" VARCHAR2(20 BYTE), 
    "GADEN" VARCHAR2(20 BYTE),
    "GIAVE" NUMBER(19,4),
    "LOAI" VARCHAR2(20 BYTE), 
    "GIODI"VARCHAR2(20 BYTE), 
    "GIODEN" VARCHAR2(20 BYTE),
     "NGAYDI"  VARCHAR2(20 BYTE), 
    "NGAYVE"  VARCHAR2(20 BYTE)
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 create table "DOAN1"."LICHSUVE"
(    
    "HOTEN" VARCHAR2(30 BYTE), 
	"GIOITINH" VARCHAR2(20 BYTE),
    
    "MAVE" NUMBER(8,0) ,
     "SOCMND" VARCHAR2(30 BYTE),
     
    "QUOCTICH" VARCHAR2(20 BYTE),
    "SDT" VARCHAR2(20 BYTE),
    
    "MASOGHE" NUMBER(8,0),
    "GADI" VARCHAR2(20 BYTE), 
    
    "GADEN" VARCHAR2(20 BYTE), 
    "LOAI" VARCHAR2(20 BYTE), 
    "TIENTRA" NUMBER(19,4),
    
    "GIODI"VARCHAR2(20 BYTE), 
    "GIODEN" VARCHAR2(20 BYTE),
    
       "NGAYDI"  VARCHAR2(20 BYTE), 
    "NGAYVE" VARCHAR2(20 BYTE),
      "NGAYBANVE" VARCHAR2(20 BYTE)
    
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  create table "DOAN1"."TAIKHOANQL"
(  "ID" NUMBER(8,0) PRIMARY KEY,
	"MATKHAU" VARCHAR2(30 BYTE)
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------
insert into "DOAN1"."TAIKHOANQL" ("ID", "MATKHAU") values(19521598, '12345');
---
insert into "DOAN1"."TAIKHOANNV" ("ID", "MATKHAU") values(19521598, '12345');
--
insert into "DOAN1"."NHANVIEN" ("MANV", "HOTEN", "SOCMND", "ID", "GIOITINH", "QUOCTICH", "SDT") values(123, 'BUI QUOC HUY', '231315216', 19521598, 'Nam', 'VN', '0963639201')
;
SELECT "GADI","GADEN",COUNT(*), SUM(TIENTRA),"NGAYBANVE"
FROM "DOAN1"."LICHSUVE"  
GROUP BY "NGAYBANVE","GADI","GADEN";
insert into "DOAN1"."LICHSUVE" ("HOTEN", "GIOITINH", "MAVE", "SOCMND", "QUOCTICH", "SDT", "MASOGHE", "GADI", "GADEN", "LOAI", "TIENTRA", "GIODI", "GIODEN", "NGAYDI", "NGAYVE", "NGAYBANVE") values('bui huy3', 'Nam', 7, '332', 'VN', '0909', 106, 'Ha Noi', 'Vung Tau', 'Mot Chieu', 200000, '20:20', '23:20', '01/06/2021', 'null', '03/06/2021')